// code segment => initialize and uninitialize segment => Stack => Heap (dynamic memory allocation)
public class DataStructureADT {
// array : collection of the element by an index
// abstract data type 

//element access in the bigO(1);
// insertion and deletion big0(n);
// new array creation 

/*

travalsal :
	big O of N
Insertion(size +1 ) and Deletion(size - 1): 
	best => at last
	worst => at first big O of N



*/

public class ArrayS{
	// Integer total_size;
	// Integer used_size;

}

}