public class Tree {
}

/*

## Trees : 
1. Root : topmost node 
2. parent : Node which connects to the child
3. Child : node which is connected by another node by the child
4. leaf/External node : node which dont have the childran ;
5. internal node : the node at least one child 
6. depth of node : height from root. i.e no of links => parent = 0 and child of parent is 1; 
7. height : number of the edges from the root to the deepest leaf node 
8. sibling : node belonging to the same node 


*/