# manual_run_with_package_backup Workflow :

name: Manual Run With Package Backup

on:
  workflow_dispatch:
    inputs:
      test_classes:
        description: 'Test classes to run'
        required: true
        default: 'null'

permissions: write-all
          
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Salesforce CLI
        shell: bash
        run: |
          npm install -g @salesforce/cli
          sf --version
      - name: Login to Environment
        shell: bash
        run: |
          sf org login sfdx-url --set-default --sfdx-url-file <(echo "${{ secrets.SFDX_INTEGRATION_URL }}")
      - name: Deploy to Environment
        shell: bash
        env:
          TEST_CLASSES: ${{ github.event.inputs.test_classes }}
        run: |
          sf project deploy start --manifest ./manifest/package.xml --wait 10 --test-level RunSpecifiedTests --tests  "$TEST_CLASSES"
      - name: Retrive From Org And Push to GIT
        shell: bash
        run: |
            git checkout main
            git config --global user.email "rushikesh.kale3@bajajfinserv.in"
            git config --global user.name "Azure DevOps"
            sf project retrieve start -x ./manifest/package.xml
            git add -A
            git commit -m "Package-Backup"
            git push https://github.com/Rushi7287/SFDC_CI_CD_ORG_7287.git
    